from Projects.mongo_data.crypto_news_data import CryptoNews
from Projects.mongo_data.mongo_init import init_mongodb
from Projects.mongo_data.settings_data import SettingsList
from Projects.mongo_data.ticker_data import TickerDataSettings, TickerData